version: '3.8'
services:
  cake4-web:
    build: .
    ports:
      - "81:80"
      - "9003:9003" # Xdebug Port
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      PHP_IDE_CONFIG: "serverName=cake4-web"
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: cake
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - backend
      
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cake
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - backend

networks:
  backend:
    driver: bridge
volumes:
  db_data:
